server:
  port: 8089
  servlet:
    context-path: /permission

spring:
  datasource:
    username: root
    password: ll03001360
    url: jdbc:mysql://localhost:3306/permission_template?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    m

mybatis:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

logging:
  level:
    com.wzy.dao: debug #打印sql


